/*
 * File:           C:\Users\Maximilian\Documents\Arduino\libraries\SigmaDSP-master\workspace\2_Sub_Box_beta\SigmaStudio_project\export\2_sub_box_IC_1_PARAM.h
 *
 * Created:        Saturday, March 26, 2022 11:52:43 AM
 * Description:    2_sub_box:IC 1 parameter RAM definitions.
 *
 * This software is distributed in the hope that it will be useful,
 * but is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
 * CONDITIONS OF ANY KIND, without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *
 * This software may only be used to program products purchased from
 * Analog Devices for incorporation by you into audio products that
 * are intended for resale to audio product end users. This software
 * may not be distributed whole or in any part to third parties.
 *
 * Copyright ©2022 Analog Devices, Inc. All rights reserved.
 */
#ifndef __2_SUB_BOX_IC_1_PARAM_H__
#define __2_SUB_BOX_IC_1_PARAM_H__


/* Module SW vol 1 - Single SW slew vol (adjustable)*/
#define MOD_SWVOL1_COUNT                               2
#define MOD_SWVOL1_DEVICE                              "IC1"
#define MOD_SWVOL1_ALG0_TARGET_ADDR                    0
#define MOD_SWVOL1_ALG0_TARGET_FIXPT                   0x00800000
#define MOD_SWVOL1_ALG0_TARGET_VALUE                   SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_SWVOL1_ALG0_TARGET_TYPE                    SIGMASTUDIOTYPE_FIXPOINT
#define MOD_SWVOL1_ALG0_STEP_ADDR                      1
#define MOD_SWVOL1_ALG0_STEP_FIXPT                     0x00000800
#define MOD_SWVOL1_ALG0_STEP_VALUE                     SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.000244140625)
#define MOD_SWVOL1_ALG0_STEP_TYPE                      SIGMASTUDIOTYPE_FIXPOINT

/* Module SW vol 3 - Single SW slew vol (adjustable)*/
#define MOD_SWVOL3_COUNT                               2
#define MOD_SWVOL3_DEVICE                              "IC1"
#define MOD_SWVOL3_ALG0_TARGET_ADDR                    2
#define MOD_SWVOL3_ALG0_TARGET_FIXPT                   0x00800000
#define MOD_SWVOL3_ALG0_TARGET_VALUE                   SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_SWVOL3_ALG0_TARGET_TYPE                    SIGMASTUDIOTYPE_FIXPOINT
#define MOD_SWVOL3_ALG0_STEP_ADDR                      3
#define MOD_SWVOL3_ALG0_STEP_FIXPT                     0x00000800
#define MOD_SWVOL3_ALG0_STEP_VALUE                     SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.000244140625)
#define MOD_SWVOL3_ALG0_STEP_TYPE                      SIGMASTUDIOTYPE_FIXPOINT

/* Module St Mixer1 - Stereo Mixer*/
#define MOD_STMIXER1_COUNT                             2
#define MOD_STMIXER1_DEVICE                            "IC1"
#define MOD_STMIXER1_ALG0_STAGE0_VOLUME_ADDR           4
#define MOD_STMIXER1_ALG0_STAGE0_VOLUME_FIXPT          0x00800000
#define MOD_STMIXER1_ALG0_STAGE0_VOLUME_VALUE          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_STMIXER1_ALG0_STAGE0_VOLUME_TYPE           SIGMASTUDIOTYPE_FIXPOINT
#define MOD_STMIXER1_ALG0_STAGE1_VOLUME_ADDR           5
#define MOD_STMIXER1_ALG0_STAGE1_VOLUME_FIXPT          0x00800000
#define MOD_STMIXER1_ALG0_STAGE1_VOLUME_VALUE          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_STMIXER1_ALG0_STAGE1_VOLUME_TYPE           SIGMASTUDIOTYPE_FIXPOINT

/* Module SW vol 2 - Single SW slew vol (adjustable)*/
#define MOD_SWVOL2_COUNT                               2
#define MOD_SWVOL2_DEVICE                              "IC1"
#define MOD_SWVOL2_ALG0_TARGET_ADDR                    6
#define MOD_SWVOL2_ALG0_TARGET_FIXPT                   0x00800000
#define MOD_SWVOL2_ALG0_TARGET_VALUE                   SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_SWVOL2_ALG0_TARGET_TYPE                    SIGMASTUDIOTYPE_FIXPOINT
#define MOD_SWVOL2_ALG0_STEP_ADDR                      7
#define MOD_SWVOL2_ALG0_STEP_FIXPT                     0x00000800
#define MOD_SWVOL2_ALG0_STEP_VALUE                     SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.000244140625)
#define MOD_SWVOL2_ALG0_STEP_TYPE                      SIGMASTUDIOTYPE_FIXPOINT

/* Module Mid EQ1 - Medium Size Eq*/
#define MOD_MIDEQ1_COUNT                               35
#define MOD_MIDEQ1_DEVICE                              "IC1"
#define MOD_MIDEQ1_ALG0_STAGE0_B0_ADDR                 8
#define MOD_MIDEQ1_ALG0_STAGE0_B0_FIXPT                0x00800000
#define MOD_MIDEQ1_ALG0_STAGE0_B0_VALUE                SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_MIDEQ1_ALG0_STAGE0_B0_TYPE                 SIGMASTUDIOTYPE_FIXPOINT
#define MOD_MIDEQ1_ALG0_STAGE0_B1_ADDR                 9
#define MOD_MIDEQ1_ALG0_STAGE0_B1_FIXPT                0x00000000
#define MOD_MIDEQ1_ALG0_STAGE0_B1_VALUE                SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_MIDEQ1_ALG0_STAGE0_B1_TYPE                 SIGMASTUDIOTYPE_FIXPOINT
#define MOD_MIDEQ1_ALG0_STAGE0_B2_ADDR                 10
#define MOD_MIDEQ1_ALG0_STAGE0_B2_FIXPT                0x00000000
#define MOD_MIDEQ1_ALG0_STAGE0_B2_VALUE                SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_MIDEQ1_ALG0_STAGE0_B2_TYPE                 SIGMASTUDIOTYPE_FIXPOINT
#define MOD_MIDEQ1_ALG0_STAGE0_A1_ADDR                 11
#define MOD_MIDEQ1_ALG0_STAGE0_A1_FIXPT                0x00000000
#define MOD_MIDEQ1_ALG0_STAGE0_A1_VALUE                SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_MIDEQ1_ALG0_STAGE0_A1_TYPE                 SIGMASTUDIOTYPE_FIXPOINT
#define MOD_MIDEQ1_ALG0_STAGE0_A2_ADDR                 12
#define MOD_MIDEQ1_ALG0_STAGE0_A2_FIXPT                0x00000000
#define MOD_MIDEQ1_ALG0_STAGE0_A2_VALUE                SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_MIDEQ1_ALG0_STAGE0_A2_TYPE                 SIGMASTUDIOTYPE_FIXPOINT
#define MOD_MIDEQ1_ALG0_STAGE1_B0_ADDR                 13
#define MOD_MIDEQ1_ALG0_STAGE1_B0_FIXPT                0x00800000
#define MOD_MIDEQ1_ALG0_STAGE1_B0_VALUE                SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_MIDEQ1_ALG0_STAGE1_B0_TYPE                 SIGMASTUDIOTYPE_FIXPOINT
#define MOD_MIDEQ1_ALG0_STAGE1_B1_ADDR                 14
#define MOD_MIDEQ1_ALG0_STAGE1_B1_FIXPT                0x00000000
#define MOD_MIDEQ1_ALG0_STAGE1_B1_VALUE                SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_MIDEQ1_ALG0_STAGE1_B1_TYPE                 SIGMASTUDIOTYPE_FIXPOINT
#define MOD_MIDEQ1_ALG0_STAGE1_B2_ADDR                 15
#define MOD_MIDEQ1_ALG0_STAGE1_B2_FIXPT                0x00000000
#define MOD_MIDEQ1_ALG0_STAGE1_B2_VALUE                SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_MIDEQ1_ALG0_STAGE1_B2_TYPE                 SIGMASTUDIOTYPE_FIXPOINT
#define MOD_MIDEQ1_ALG0_STAGE1_A1_ADDR                 16
#define MOD_MIDEQ1_ALG0_STAGE1_A1_FIXPT                0x00000000
#define MOD_MIDEQ1_ALG0_STAGE1_A1_VALUE                SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_MIDEQ1_ALG0_STAGE1_A1_TYPE                 SIGMASTUDIOTYPE_FIXPOINT
#define MOD_MIDEQ1_ALG0_STAGE1_A2_ADDR                 17
#define MOD_MIDEQ1_ALG0_STAGE1_A2_FIXPT                0x00000000
#define MOD_MIDEQ1_ALG0_STAGE1_A2_VALUE                SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_MIDEQ1_ALG0_STAGE1_A2_TYPE                 SIGMASTUDIOTYPE_FIXPOINT
#define MOD_MIDEQ1_ALG0_STAGE2_B0_ADDR                 18
#define MOD_MIDEQ1_ALG0_STAGE2_B0_FIXPT                0x00800000
#define MOD_MIDEQ1_ALG0_STAGE2_B0_VALUE                SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_MIDEQ1_ALG0_STAGE2_B0_TYPE                 SIGMASTUDIOTYPE_FIXPOINT
#define MOD_MIDEQ1_ALG0_STAGE2_B1_ADDR                 19
#define MOD_MIDEQ1_ALG0_STAGE2_B1_FIXPT                0x00000000
#define MOD_MIDEQ1_ALG0_STAGE2_B1_VALUE                SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_MIDEQ1_ALG0_STAGE2_B1_TYPE                 SIGMASTUDIOTYPE_FIXPOINT
#define MOD_MIDEQ1_ALG0_STAGE2_B2_ADDR                 20
#define MOD_MIDEQ1_ALG0_STAGE2_B2_FIXPT                0x00000000
#define MOD_MIDEQ1_ALG0_STAGE2_B2_VALUE                SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_MIDEQ1_ALG0_STAGE2_B2_TYPE                 SIGMASTUDIOTYPE_FIXPOINT
#define MOD_MIDEQ1_ALG0_STAGE2_A1_ADDR                 21
#define MOD_MIDEQ1_ALG0_STAGE2_A1_FIXPT                0x00000000
#define MOD_MIDEQ1_ALG0_STAGE2_A1_VALUE                SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_MIDEQ1_ALG0_STAGE2_A1_TYPE                 SIGMASTUDIOTYPE_FIXPOINT
#define MOD_MIDEQ1_ALG0_STAGE2_A2_ADDR                 22
#define MOD_MIDEQ1_ALG0_STAGE2_A2_FIXPT                0x00000000
#define MOD_MIDEQ1_ALG0_STAGE2_A2_VALUE                SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_MIDEQ1_ALG0_STAGE2_A2_TYPE                 SIGMASTUDIOTYPE_FIXPOINT
#define MOD_MIDEQ1_ALG0_STAGE3_B0_ADDR                 23
#define MOD_MIDEQ1_ALG0_STAGE3_B0_FIXPT                0x00800000
#define MOD_MIDEQ1_ALG0_STAGE3_B0_VALUE                SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_MIDEQ1_ALG0_STAGE3_B0_TYPE                 SIGMASTUDIOTYPE_FIXPOINT
#define MOD_MIDEQ1_ALG0_STAGE3_B1_ADDR                 24
#define MOD_MIDEQ1_ALG0_STAGE3_B1_FIXPT                0x00000000
#define MOD_MIDEQ1_ALG0_STAGE3_B1_VALUE                SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_MIDEQ1_ALG0_STAGE3_B1_TYPE                 SIGMASTUDIOTYPE_FIXPOINT
#define MOD_MIDEQ1_ALG0_STAGE3_B2_ADDR                 25
#define MOD_MIDEQ1_ALG0_STAGE3_B2_FIXPT                0x00000000
#define MOD_MIDEQ1_ALG0_STAGE3_B2_VALUE                SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_MIDEQ1_ALG0_STAGE3_B2_TYPE                 SIGMASTUDIOTYPE_FIXPOINT
#define MOD_MIDEQ1_ALG0_STAGE3_A1_ADDR                 26
#define MOD_MIDEQ1_ALG0_STAGE3_A1_FIXPT                0x00000000
#define MOD_MIDEQ1_ALG0_STAGE3_A1_VALUE                SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_MIDEQ1_ALG0_STAGE3_A1_TYPE                 SIGMASTUDIOTYPE_FIXPOINT
#define MOD_MIDEQ1_ALG0_STAGE3_A2_ADDR                 27
#define MOD_MIDEQ1_ALG0_STAGE3_A2_FIXPT                0x00000000
#define MOD_MIDEQ1_ALG0_STAGE3_A2_VALUE                SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_MIDEQ1_ALG0_STAGE3_A2_TYPE                 SIGMASTUDIOTYPE_FIXPOINT
#define MOD_MIDEQ1_ALG0_STAGE4_B0_ADDR                 28
#define MOD_MIDEQ1_ALG0_STAGE4_B0_FIXPT                0x00800000
#define MOD_MIDEQ1_ALG0_STAGE4_B0_VALUE                SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_MIDEQ1_ALG0_STAGE4_B0_TYPE                 SIGMASTUDIOTYPE_FIXPOINT
#define MOD_MIDEQ1_ALG0_STAGE4_B1_ADDR                 29
#define MOD_MIDEQ1_ALG0_STAGE4_B1_FIXPT                0x00000000
#define MOD_MIDEQ1_ALG0_STAGE4_B1_VALUE                SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_MIDEQ1_ALG0_STAGE4_B1_TYPE                 SIGMASTUDIOTYPE_FIXPOINT
#define MOD_MIDEQ1_ALG0_STAGE4_B2_ADDR                 30
#define MOD_MIDEQ1_ALG0_STAGE4_B2_FIXPT                0x00000000
#define MOD_MIDEQ1_ALG0_STAGE4_B2_VALUE                SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_MIDEQ1_ALG0_STAGE4_B2_TYPE                 SIGMASTUDIOTYPE_FIXPOINT
#define MOD_MIDEQ1_ALG0_STAGE4_A1_ADDR                 31
#define MOD_MIDEQ1_ALG0_STAGE4_A1_FIXPT                0x00000000
#define MOD_MIDEQ1_ALG0_STAGE4_A1_VALUE                SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_MIDEQ1_ALG0_STAGE4_A1_TYPE                 SIGMASTUDIOTYPE_FIXPOINT
#define MOD_MIDEQ1_ALG0_STAGE4_A2_ADDR                 32
#define MOD_MIDEQ1_ALG0_STAGE4_A2_FIXPT                0x00000000
#define MOD_MIDEQ1_ALG0_STAGE4_A2_VALUE                SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_MIDEQ1_ALG0_STAGE4_A2_TYPE                 SIGMASTUDIOTYPE_FIXPOINT
#define MOD_MIDEQ1_ALG0_STAGE5_B0_ADDR                 33
#define MOD_MIDEQ1_ALG0_STAGE5_B0_FIXPT                0x00800000
#define MOD_MIDEQ1_ALG0_STAGE5_B0_VALUE                SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_MIDEQ1_ALG0_STAGE5_B0_TYPE                 SIGMASTUDIOTYPE_FIXPOINT
#define MOD_MIDEQ1_ALG0_STAGE5_B1_ADDR                 34
#define MOD_MIDEQ1_ALG0_STAGE5_B1_FIXPT                0x00000000
#define MOD_MIDEQ1_ALG0_STAGE5_B1_VALUE                SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_MIDEQ1_ALG0_STAGE5_B1_TYPE                 SIGMASTUDIOTYPE_FIXPOINT
#define MOD_MIDEQ1_ALG0_STAGE5_B2_ADDR                 35
#define MOD_MIDEQ1_ALG0_STAGE5_B2_FIXPT                0x00000000
#define MOD_MIDEQ1_ALG0_STAGE5_B2_VALUE                SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_MIDEQ1_ALG0_STAGE5_B2_TYPE                 SIGMASTUDIOTYPE_FIXPOINT
#define MOD_MIDEQ1_ALG0_STAGE5_A1_ADDR                 36
#define MOD_MIDEQ1_ALG0_STAGE5_A1_FIXPT                0x00000000
#define MOD_MIDEQ1_ALG0_STAGE5_A1_VALUE                SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_MIDEQ1_ALG0_STAGE5_A1_TYPE                 SIGMASTUDIOTYPE_FIXPOINT
#define MOD_MIDEQ1_ALG0_STAGE5_A2_ADDR                 37
#define MOD_MIDEQ1_ALG0_STAGE5_A2_FIXPT                0x00000000
#define MOD_MIDEQ1_ALG0_STAGE5_A2_VALUE                SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_MIDEQ1_ALG0_STAGE5_A2_TYPE                 SIGMASTUDIOTYPE_FIXPOINT
#define MOD_MIDEQ1_ALG0_STAGE6_B0_ADDR                 38
#define MOD_MIDEQ1_ALG0_STAGE6_B0_FIXPT                0x00800000
#define MOD_MIDEQ1_ALG0_STAGE6_B0_VALUE                SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_MIDEQ1_ALG0_STAGE6_B0_TYPE                 SIGMASTUDIOTYPE_FIXPOINT
#define MOD_MIDEQ1_ALG0_STAGE6_B1_ADDR                 39
#define MOD_MIDEQ1_ALG0_STAGE6_B1_FIXPT                0x00000000
#define MOD_MIDEQ1_ALG0_STAGE6_B1_VALUE                SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_MIDEQ1_ALG0_STAGE6_B1_TYPE                 SIGMASTUDIOTYPE_FIXPOINT
#define MOD_MIDEQ1_ALG0_STAGE6_B2_ADDR                 40
#define MOD_MIDEQ1_ALG0_STAGE6_B2_FIXPT                0x00000000
#define MOD_MIDEQ1_ALG0_STAGE6_B2_VALUE                SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_MIDEQ1_ALG0_STAGE6_B2_TYPE                 SIGMASTUDIOTYPE_FIXPOINT
#define MOD_MIDEQ1_ALG0_STAGE6_A1_ADDR                 41
#define MOD_MIDEQ1_ALG0_STAGE6_A1_FIXPT                0x00000000
#define MOD_MIDEQ1_ALG0_STAGE6_A1_VALUE                SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_MIDEQ1_ALG0_STAGE6_A1_TYPE                 SIGMASTUDIOTYPE_FIXPOINT
#define MOD_MIDEQ1_ALG0_STAGE6_A2_ADDR                 42
#define MOD_MIDEQ1_ALG0_STAGE6_A2_FIXPT                0x00000000
#define MOD_MIDEQ1_ALG0_STAGE6_A2_VALUE                SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_MIDEQ1_ALG0_STAGE6_A2_TYPE                 SIGMASTUDIOTYPE_FIXPOINT

/* Module S Mixer1 - Single Control Mixer*/
#define MOD_SMIXER1_COUNT                              1
#define MOD_SMIXER1_DEVICE                             "IC1"
#define MOD_SMIXER1_SINGLECTRLMIXERNEW19401_ADDR       43
#define MOD_SMIXER1_SINGLECTRLMIXERNEW19401_FIXPT      0x00800000
#define MOD_SMIXER1_SINGLECTRLMIXERNEW19401_VALUE      SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_SMIXER1_SINGLECTRLMIXERNEW19401_TYPE       SIGMASTUDIOTYPE_FIXPOINT

/* Module Limiter 1 - Limiter*/
#define MOD_LIMITER1_COUNT                             15
#define MOD_LIMITER1_DEVICE                            "IC1"
#define MOD_LIMITER1_ALG0_S1_ADDR                      44
#define MOD_LIMITER1_ALG0_S1_FIXPT                     0xFFFE2BE3
#define MOD_LIMITER1_ALG0_S1_VALUE                     SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.01428571428571)
#define MOD_LIMITER1_ALG0_S1_TYPE                      SIGMASTUDIOTYPE_FIXPOINT
#define MOD_LIMITER1_ALG0_INT1_ADDR                    45
#define MOD_LIMITER1_ALG0_INT1_FIXPT                   0x0022BE2B
#define MOD_LIMITER1_ALG0_INT1_VALUE                   SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.27142857142857)
#define MOD_LIMITER1_ALG0_INT1_TYPE                    SIGMASTUDIOTYPE_FIXPOINT
#define MOD_LIMITER1_ALG0_S2_ADDR                      46
#define MOD_LIMITER1_ALG0_S2_FIXPT                     0xFFEAAAAB
#define MOD_LIMITER1_ALG0_S2_VALUE                     SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.16666666666667)
#define MOD_LIMITER1_ALG0_S2_TYPE                      SIGMASTUDIOTYPE_FIXPOINT
#define MOD_LIMITER1_ALG0_INT2_ADDR                    47
#define MOD_LIMITER1_ALG0_INT2_FIXPT                   0x006AAAAA
#define MOD_LIMITER1_ALG0_INT2_VALUE                   SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.8333333333333)
#define MOD_LIMITER1_ALG0_INT2_TYPE                    SIGMASTUDIOTYPE_FIXPOINT
#define MOD_LIMITER1_ALG0_S3_ADDR                      48
#define MOD_LIMITER1_ALG0_S3_FIXPT                     0xFF9A69A7
#define MOD_LIMITER1_ALG0_S3_VALUE                     SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.79365079365079)
#define MOD_LIMITER1_ALG0_S3_TYPE                      SIGMASTUDIOTYPE_FIXPOINT
#define MOD_LIMITER1_ALG0_INT3_ADDR                    49
#define MOD_LIMITER1_ALG0_INT3_FIXPT                   0x00FDF7DF
#define MOD_LIMITER1_ALG0_INT3_VALUE                   SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1.98412698412698)
#define MOD_LIMITER1_ALG0_INT3_TYPE                    SIGMASTUDIOTYPE_FIXPOINT
#define MOD_LIMITER1_ALG0_S4_ADDR                      50
#define MOD_LIMITER1_ALG0_S4_FIXPT                     0xF83C6C20
#define MOD_LIMITER1_ALG0_S4_VALUE                     SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-15.527950310559)
#define MOD_LIMITER1_ALG0_S4_TYPE                      SIGMASTUDIOTYPE_FIXPOINT
#define MOD_LIMITER1_ALG0_INT4_ADDR                    51
#define MOD_LIMITER1_ALG0_INT4_FIXPT                   0x03F5AA22
#define MOD_LIMITER1_ALG0_INT4_VALUE                   SIGMASTUDIOTYPE_FIXPOINT_CONVERT(7.91925465838509)
#define MOD_LIMITER1_ALG0_INT4_TYPE                    SIGMASTUDIOTYPE_FIXPOINT
#define MOD_LIMITER1_ALG0_C1_ADDR                      52
#define MOD_LIMITER1_ALG0_C1_FIXPT                     0x01800000
#define MOD_LIMITER1_ALG0_C1_VALUE                     SIGMASTUDIOTYPE_FIXPOINT_CONVERT(3)
#define MOD_LIMITER1_ALG0_C1_TYPE                      SIGMASTUDIOTYPE_FIXPOINT
#define MOD_LIMITER1_ALG0_C2_ADDR                      53
#define MOD_LIMITER1_ALG0_C2_FIXPT                     0x01000000
#define MOD_LIMITER1_ALG0_C2_VALUE                     SIGMASTUDIOTYPE_FIXPOINT_CONVERT(2)
#define MOD_LIMITER1_ALG0_C2_TYPE                      SIGMASTUDIOTYPE_FIXPOINT
#define MOD_LIMITER1_ALG0_C3_ADDR                      54
#define MOD_LIMITER1_ALG0_C3_FIXPT                     0x00333333
#define MOD_LIMITER1_ALG0_C3_VALUE                     SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.4)
#define MOD_LIMITER1_ALG0_C3_TYPE                      SIGMASTUDIOTYPE_FIXPOINT
#define MOD_LIMITER1_ALG0_THRESHOLD_ADDR               55
#define MOD_LIMITER1_ALG0_THRESHOLD_FIXPT              0x00800000
#define MOD_LIMITER1_ALG0_THRESHOLD_VALUE              SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_LIMITER1_ALG0_THRESHOLD_TYPE               SIGMASTUDIOTYPE_FIXPOINT
#define MOD_LIMITER1_ALG0_RMS_ADDR                     56
#define MOD_LIMITER1_ALG0_RMS_FIXPT                    0x000007DC
#define MOD_LIMITER1_ALG0_RMS_VALUE                    SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.000239881380791562)
#define MOD_LIMITER1_ALG0_RMS_TYPE                     SIGMASTUDIOTYPE_FIXPOINT
#define MOD_LIMITER1_ALG0_DECAY_ADDR                   57
#define MOD_LIMITER1_ALG0_DECAY_FIXPT                  0x00000800
#define MOD_LIMITER1_ALG0_DECAY_VALUE                  SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.000244140625)
#define MOD_LIMITER1_ALG0_DECAY_TYPE                   SIGMASTUDIOTYPE_FIXPOINT
#define MOD_LIMITER1_ALG0_DECAYCOMPLEMENT_ADDR         58
#define MOD_LIMITER1_ALG0_DECAYCOMPLEMENT_FIXPT        0x007FF000
#define MOD_LIMITER1_ALG0_DECAYCOMPLEMENT_VALUE        SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.99951171875)
#define MOD_LIMITER1_ALG0_DECAYCOMPLEMENT_TYPE         SIGMASTUDIOTYPE_FIXPOINT

/* Module Limiter 2 - Limiter*/
#define MOD_LIMITER2_COUNT                             15
#define MOD_LIMITER2_DEVICE                            "IC1"
#define MOD_LIMITER2_ALG0_S1_ADDR                      59
#define MOD_LIMITER2_ALG0_S1_FIXPT                     0xFFFE2BE3
#define MOD_LIMITER2_ALG0_S1_VALUE                     SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.01428571428571)
#define MOD_LIMITER2_ALG0_S1_TYPE                      SIGMASTUDIOTYPE_FIXPOINT
#define MOD_LIMITER2_ALG0_INT1_ADDR                    60
#define MOD_LIMITER2_ALG0_INT1_FIXPT                   0x0022BE2B
#define MOD_LIMITER2_ALG0_INT1_VALUE                   SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.27142857142857)
#define MOD_LIMITER2_ALG0_INT1_TYPE                    SIGMASTUDIOTYPE_FIXPOINT
#define MOD_LIMITER2_ALG0_S2_ADDR                      61
#define MOD_LIMITER2_ALG0_S2_FIXPT                     0xFFEAAAAB
#define MOD_LIMITER2_ALG0_S2_VALUE                     SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.16666666666667)
#define MOD_LIMITER2_ALG0_S2_TYPE                      SIGMASTUDIOTYPE_FIXPOINT
#define MOD_LIMITER2_ALG0_INT2_ADDR                    62
#define MOD_LIMITER2_ALG0_INT2_FIXPT                   0x006AAAAA
#define MOD_LIMITER2_ALG0_INT2_VALUE                   SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.8333333333333)
#define MOD_LIMITER2_ALG0_INT2_TYPE                    SIGMASTUDIOTYPE_FIXPOINT
#define MOD_LIMITER2_ALG0_S3_ADDR                      63
#define MOD_LIMITER2_ALG0_S3_FIXPT                     0xFF9A69A7
#define MOD_LIMITER2_ALG0_S3_VALUE                     SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.79365079365079)
#define MOD_LIMITER2_ALG0_S3_TYPE                      SIGMASTUDIOTYPE_FIXPOINT
#define MOD_LIMITER2_ALG0_INT3_ADDR                    64
#define MOD_LIMITER2_ALG0_INT3_FIXPT                   0x00FDF7DF
#define MOD_LIMITER2_ALG0_INT3_VALUE                   SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1.98412698412698)
#define MOD_LIMITER2_ALG0_INT3_TYPE                    SIGMASTUDIOTYPE_FIXPOINT
#define MOD_LIMITER2_ALG0_S4_ADDR                      65
#define MOD_LIMITER2_ALG0_S4_FIXPT                     0xF83C6C20
#define MOD_LIMITER2_ALG0_S4_VALUE                     SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-15.527950310559)
#define MOD_LIMITER2_ALG0_S4_TYPE                      SIGMASTUDIOTYPE_FIXPOINT
#define MOD_LIMITER2_ALG0_INT4_ADDR                    66
#define MOD_LIMITER2_ALG0_INT4_FIXPT                   0x03F5AA22
#define MOD_LIMITER2_ALG0_INT4_VALUE                   SIGMASTUDIOTYPE_FIXPOINT_CONVERT(7.91925465838509)
#define MOD_LIMITER2_ALG0_INT4_TYPE                    SIGMASTUDIOTYPE_FIXPOINT
#define MOD_LIMITER2_ALG0_C1_ADDR                      67
#define MOD_LIMITER2_ALG0_C1_FIXPT                     0x01800000
#define MOD_LIMITER2_ALG0_C1_VALUE                     SIGMASTUDIOTYPE_FIXPOINT_CONVERT(3)
#define MOD_LIMITER2_ALG0_C1_TYPE                      SIGMASTUDIOTYPE_FIXPOINT
#define MOD_LIMITER2_ALG0_C2_ADDR                      68
#define MOD_LIMITER2_ALG0_C2_FIXPT                     0x01000000
#define MOD_LIMITER2_ALG0_C2_VALUE                     SIGMASTUDIOTYPE_FIXPOINT_CONVERT(2)
#define MOD_LIMITER2_ALG0_C2_TYPE                      SIGMASTUDIOTYPE_FIXPOINT
#define MOD_LIMITER2_ALG0_C3_ADDR                      69
#define MOD_LIMITER2_ALG0_C3_FIXPT                     0x00333333
#define MOD_LIMITER2_ALG0_C3_VALUE                     SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.4)
#define MOD_LIMITER2_ALG0_C3_TYPE                      SIGMASTUDIOTYPE_FIXPOINT
#define MOD_LIMITER2_ALG0_THRESHOLD_ADDR               70
#define MOD_LIMITER2_ALG0_THRESHOLD_FIXPT              0x00800000
#define MOD_LIMITER2_ALG0_THRESHOLD_VALUE              SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_LIMITER2_ALG0_THRESHOLD_TYPE               SIGMASTUDIOTYPE_FIXPOINT
#define MOD_LIMITER2_ALG0_RMS_ADDR                     71
#define MOD_LIMITER2_ALG0_RMS_FIXPT                    0x000007DC
#define MOD_LIMITER2_ALG0_RMS_VALUE                    SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.000239881380791562)
#define MOD_LIMITER2_ALG0_RMS_TYPE                     SIGMASTUDIOTYPE_FIXPOINT
#define MOD_LIMITER2_ALG0_DECAY_ADDR                   72
#define MOD_LIMITER2_ALG0_DECAY_FIXPT                  0x00000800
#define MOD_LIMITER2_ALG0_DECAY_VALUE                  SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.000244140625)
#define MOD_LIMITER2_ALG0_DECAY_TYPE                   SIGMASTUDIOTYPE_FIXPOINT
#define MOD_LIMITER2_ALG0_DECAYCOMPLEMENT_ADDR         73
#define MOD_LIMITER2_ALG0_DECAYCOMPLEMENT_FIXPT        0x007FF000
#define MOD_LIMITER2_ALG0_DECAYCOMPLEMENT_VALUE        SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.99951171875)
#define MOD_LIMITER2_ALG0_DECAYCOMPLEMENT_TYPE         SIGMASTUDIOTYPE_FIXPOINT

/* Module Gen 1st Order1 - General (1st order)*/
#define MOD_GEN1STORDER1_COUNT                         3
#define MOD_GEN1STORDER1_DEVICE                        "IC1"
#define MOD_GEN1STORDER1_ALG0_PARAMB00_ADDR            74
#define MOD_GEN1STORDER1_ALG0_PARAMB00_FIXPT           0x00000C97
#define MOD_GEN1STORDER1_ALG0_PARAMB00_VALUE           SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.00038430653507388)
#define MOD_GEN1STORDER1_ALG0_PARAMB00_TYPE            SIGMASTUDIOTYPE_FIXPOINT
#define MOD_GEN1STORDER1_ALG0_PARAMB10_ADDR            75
#define MOD_GEN1STORDER1_ALG0_PARAMB10_FIXPT           0x00000000
#define MOD_GEN1STORDER1_ALG0_PARAMB10_VALUE           SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_GEN1STORDER1_ALG0_PARAMB10_TYPE            SIGMASTUDIOTYPE_FIXPOINT
#define MOD_GEN1STORDER1_ALG0_PARAMA00_ADDR            76
#define MOD_GEN1STORDER1_ALG0_PARAMA00_FIXPT           0x007E58B8
#define MOD_GEN1STORDER1_ALG0_PARAMA00_VALUE           SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.987082520837763)
#define MOD_GEN1STORDER1_ALG0_PARAMA00_TYPE            SIGMASTUDIOTYPE_FIXPOINT

/* Module SW vol 4 - Single SW slew vol (adjustable)*/
#define MOD_SWVOL4_COUNT                               2
#define MOD_SWVOL4_DEVICE                              "IC1"
#define MOD_SWVOL4_ALG0_TARGET_ADDR                    77
#define MOD_SWVOL4_ALG0_TARGET_FIXPT                   0x00800000
#define MOD_SWVOL4_ALG0_TARGET_VALUE                   SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_SWVOL4_ALG0_TARGET_TYPE                    SIGMASTUDIOTYPE_FIXPOINT
#define MOD_SWVOL4_ALG0_STEP_ADDR                      78
#define MOD_SWVOL4_ALG0_STEP_FIXPT                     0x00000800
#define MOD_SWVOL4_ALG0_STEP_VALUE                     SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.000244140625)
#define MOD_SWVOL4_ALG0_STEP_TYPE                      SIGMASTUDIOTYPE_FIXPOINT

/* Module Limiter 3 - Limiter*/
#define MOD_LIMITER3_COUNT                             15
#define MOD_LIMITER3_DEVICE                            "IC1"
#define MOD_LIMITER3_ALG0_S1_ADDR                      79
#define MOD_LIMITER3_ALG0_S1_FIXPT                     0xFFFE2BE3
#define MOD_LIMITER3_ALG0_S1_VALUE                     SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.01428571428571)
#define MOD_LIMITER3_ALG0_S1_TYPE                      SIGMASTUDIOTYPE_FIXPOINT
#define MOD_LIMITER3_ALG0_INT1_ADDR                    80
#define MOD_LIMITER3_ALG0_INT1_FIXPT                   0x0022BE2B
#define MOD_LIMITER3_ALG0_INT1_VALUE                   SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.27142857142857)
#define MOD_LIMITER3_ALG0_INT1_TYPE                    SIGMASTUDIOTYPE_FIXPOINT
#define MOD_LIMITER3_ALG0_S2_ADDR                      81
#define MOD_LIMITER3_ALG0_S2_FIXPT                     0xFFEAAAAB
#define MOD_LIMITER3_ALG0_S2_VALUE                     SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.16666666666667)
#define MOD_LIMITER3_ALG0_S2_TYPE                      SIGMASTUDIOTYPE_FIXPOINT
#define MOD_LIMITER3_ALG0_INT2_ADDR                    82
#define MOD_LIMITER3_ALG0_INT2_FIXPT                   0x006AAAAA
#define MOD_LIMITER3_ALG0_INT2_VALUE                   SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.8333333333333)
#define MOD_LIMITER3_ALG0_INT2_TYPE                    SIGMASTUDIOTYPE_FIXPOINT
#define MOD_LIMITER3_ALG0_S3_ADDR                      83
#define MOD_LIMITER3_ALG0_S3_FIXPT                     0xFF9A69A7
#define MOD_LIMITER3_ALG0_S3_VALUE                     SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.79365079365079)
#define MOD_LIMITER3_ALG0_S3_TYPE                      SIGMASTUDIOTYPE_FIXPOINT
#define MOD_LIMITER3_ALG0_INT3_ADDR                    84
#define MOD_LIMITER3_ALG0_INT3_FIXPT                   0x00FDF7DF
#define MOD_LIMITER3_ALG0_INT3_VALUE                   SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1.98412698412698)
#define MOD_LIMITER3_ALG0_INT3_TYPE                    SIGMASTUDIOTYPE_FIXPOINT
#define MOD_LIMITER3_ALG0_S4_ADDR                      85
#define MOD_LIMITER3_ALG0_S4_FIXPT                     0xF83C6C20
#define MOD_LIMITER3_ALG0_S4_VALUE                     SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-15.527950310559)
#define MOD_LIMITER3_ALG0_S4_TYPE                      SIGMASTUDIOTYPE_FIXPOINT
#define MOD_LIMITER3_ALG0_INT4_ADDR                    86
#define MOD_LIMITER3_ALG0_INT4_FIXPT                   0x03F5AA22
#define MOD_LIMITER3_ALG0_INT4_VALUE                   SIGMASTUDIOTYPE_FIXPOINT_CONVERT(7.91925465838509)
#define MOD_LIMITER3_ALG0_INT4_TYPE                    SIGMASTUDIOTYPE_FIXPOINT
#define MOD_LIMITER3_ALG0_C1_ADDR                      87
#define MOD_LIMITER3_ALG0_C1_FIXPT                     0x01800000
#define MOD_LIMITER3_ALG0_C1_VALUE                     SIGMASTUDIOTYPE_FIXPOINT_CONVERT(3)
#define MOD_LIMITER3_ALG0_C1_TYPE                      SIGMASTUDIOTYPE_FIXPOINT
#define MOD_LIMITER3_ALG0_C2_ADDR                      88
#define MOD_LIMITER3_ALG0_C2_FIXPT                     0x01000000
#define MOD_LIMITER3_ALG0_C2_VALUE                     SIGMASTUDIOTYPE_FIXPOINT_CONVERT(2)
#define MOD_LIMITER3_ALG0_C2_TYPE                      SIGMASTUDIOTYPE_FIXPOINT
#define MOD_LIMITER3_ALG0_C3_ADDR                      89
#define MOD_LIMITER3_ALG0_C3_FIXPT                     0x00333333
#define MOD_LIMITER3_ALG0_C3_VALUE                     SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.4)
#define MOD_LIMITER3_ALG0_C3_TYPE                      SIGMASTUDIOTYPE_FIXPOINT
#define MOD_LIMITER3_ALG0_THRESHOLD_ADDR               90
#define MOD_LIMITER3_ALG0_THRESHOLD_FIXPT              0x00800000
#define MOD_LIMITER3_ALG0_THRESHOLD_VALUE              SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_LIMITER3_ALG0_THRESHOLD_TYPE               SIGMASTUDIOTYPE_FIXPOINT
#define MOD_LIMITER3_ALG0_RMS_ADDR                     91
#define MOD_LIMITER3_ALG0_RMS_FIXPT                    0x000007DC
#define MOD_LIMITER3_ALG0_RMS_VALUE                    SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.000239881380791562)
#define MOD_LIMITER3_ALG0_RMS_TYPE                     SIGMASTUDIOTYPE_FIXPOINT
#define MOD_LIMITER3_ALG0_DECAY_ADDR                   92
#define MOD_LIMITER3_ALG0_DECAY_FIXPT                  0x00000800
#define MOD_LIMITER3_ALG0_DECAY_VALUE                  SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.000244140625)
#define MOD_LIMITER3_ALG0_DECAY_TYPE                   SIGMASTUDIOTYPE_FIXPOINT
#define MOD_LIMITER3_ALG0_DECAYCOMPLEMENT_ADDR         93
#define MOD_LIMITER3_ALG0_DECAYCOMPLEMENT_FIXPT        0x007FF000
#define MOD_LIMITER3_ALG0_DECAYCOMPLEMENT_VALUE        SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.99951171875)
#define MOD_LIMITER3_ALG0_DECAYCOMPLEMENT_TYPE         SIGMASTUDIOTYPE_FIXPOINT

#endif
